Feature/tasks
Kid-Guru/task_manager pull request #18
Opened 2021-05-23 09:20 UTC by Kid-Guru

2021-05-24 19:04 UTC, Ensaphelon requested changes

2021-05-24 19:04 UTC, Ensaphelon commented on app/javascript/components/AddPopup/AddPopup.js
> +    onCreateCard(task).catch((error) => {
onCreateCard -> onCardCreate

используй правило  `on{Object}{Action}`

проверь везде

2021-05-24 19:04 UTC, Ensaphelon commented on app/javascript/components/AddPopup/AddPopup.js
> +  const handleChangeTextField = (fieldName) => (event) => changeTask({ ...task, [fieldName]: event.target.value });
const handleChangeTextField = ({ target: { name, value }}) => changeTask({ ...task, [name]: value });

2021-05-24 19:04 UTC, Ensaphelon commented on app/javascript/components/AddPopup/AddPopup.js
> +              onChange={handleChangeTextField('name')}
```onChange={handleChangeTextField}```

2021-05-24 19:04 UTC, Ensaphelon commented on app/javascript/components/AddPopup/AddPopup.js
> +              onChange={handleChangeTextField('description')}
onChange={handleChangeTextField}

2021-05-24 19:04 UTC, Ensaphelon commented on app/javascript/components/ColumnHeader/ColumnHeader.js
> +  const count = cards.length;
const { length: count } = cards;

2021-05-24 19:04 UTC, Ensaphelon commented on app/javascript/components/ColumnHeader/ColumnHeader.js
> +          <IconButton aria-label="Load more" onClick={() => handleLoadMore()}>
onClick={handleLoadMore}

2021-05-24 19:04 UTC, Ensaphelon commented on app/javascript/components/AddPopup/AddPopup.js
> +  const handleCreate = () => {
не понятно что создает эта функция, надо отразить это в ее названии

2021-05-24 19:04 UTC, Ensaphelon commented on app/javascript/components/EditPopup/EditPopup.js
> +const EditPopup = ({ cardId, onClose, onCardDestroy, onLoadCard, onCardUpdate }) => {
onCardLoad

2021-05-24 19:04 UTC, Ensaphelon commented on app/javascript/components/EditPopup/EditPopup.js
> +    setSaving(true);
какое отношение процесс saving имеет к удалению карточки?

2021-05-24 19:04 UTC, Ensaphelon commented on app/javascript/components/EditPopup/EditPopup.js
> +      setSaving(false);
то же самое

2021-05-24 19:04 UTC, Ensaphelon commented on app/javascript/components/EditPopup/EditPopup.js
> +            disabled={isLoading || isSaving}
кажется состояние этой кнопки и той что повыше зависит от одних и тех же данных, давай создадим константу под это дело

2021-05-24 19:04 UTC, Ensaphelon commented on app/javascript/components/EditPopup/Form.js
> +        onChange={handleChangeTextField('description')}
handleTextFieldChange

2021-05-24 19:04 UTC, Ensaphelon commented on app/javascript/components/EditPopup/Form.js
> +        onChange={handleChangeTextField('name')}
handleTextFieldChange

2021-05-24 19:04 UTC, Ensaphelon commented on app/javascript/components/Task/Task.js
> +  const handleClick = () => onClick(task);
handleClick`What`?

2021-05-24 19:04 UTC, Ensaphelon commented on app/javascript/components/ColumnHeader/ColumnHeader.js
> +  const handleLoadMore = () => onLoadMore(id, currentPage + 1);
handleMoreLoad

2021-05-24 19:04 UTC, Ensaphelon commented on app/javascript/components/TaskBoard/TaskBoard.js
> +    setBoard(boardGen);
можно объект засунуть сюда не создавая вспомогательную переменную

2021-05-24 19:04 UTC, Ensaphelon commented on app/javascript/components/TaskBoard/TaskBoard.js
> +  useEffect(() => loadBoard(), []);
useEffect(loadBoard, []);

2021-05-24 19:04 UTC, Ensaphelon commented on app/javascript/components/TaskBoard/TaskBoard.js
> +  useEffect(() => generateBoard(), [boardCards]);
то же самое

2021-05-28 09:49 UTC, Kid-Guru commented on app/javascript/components/AddPopup/AddPopup.js
> +    onCreateCard(task).catch((error) => {
поправил

2021-05-28 09:50 UTC, Kid-Guru commented on app/javascript/components/AddPopup/AddPopup.js
> +  const handleChangeTextField = (fieldName) => (event) => changeTask({ ...task, [fieldName]: event.target.value });
поправил

2021-05-28 09:50 UTC, Kid-Guru commented on app/javascript/components/AddPopup/AddPopup.js
> +              onChange={handleChangeTextField('name')}
поправил

2021-05-28 09:50 UTC, Kid-Guru commented on app/javascript/components/AddPopup/AddPopup.js
> +              onChange={handleChangeTextField('description')}
поправил

2021-05-28 09:50 UTC, Kid-Guru commented on app/javascript/components/ColumnHeader/ColumnHeader.js
> +  const count = cards.length;
поправил

2021-05-28 09:50 UTC, Kid-Guru commented on app/javascript/components/Task/Task.js
> +  const handleClick = () => onClick(task);
поправил

2021-05-28 09:50 UTC, Kid-Guru commented on app/javascript/components/ColumnHeader/ColumnHeader.js
> +          <IconButton aria-label="Load more" onClick={() => handleLoadMore()}>
поправил

2021-05-28 09:50 UTC, Kid-Guru commented on app/javascript/components/AddPopup/AddPopup.js
> +  const handleCreate = () => {
поправил

2021-05-28 09:50 UTC, Kid-Guru commented on app/javascript/components/EditPopup/EditPopup.js
> +const EditPopup = ({ cardId, onClose, onCardDestroy, onLoadCard, onCardUpdate }) => {
поправил

2021-05-28 09:50 UTC, Kid-Guru commented on app/javascript/components/EditPopup/EditPopup.js
> +    setSaving(true);
поправил

2021-05-28 09:50 UTC, Kid-Guru commented on app/javascript/components/EditPopup/EditPopup.js
> +            disabled={isLoading || isSaving}
поправил

2021-05-28 09:50 UTC, Kid-Guru commented on app/javascript/components/EditPopup/Form.js
> +        onChange={handleChangeTextField('name')}
поправил

2021-05-28 09:50 UTC, Kid-Guru commented on app/javascript/components/ColumnHeader/ColumnHeader.js
> +  const handleLoadMore = () => onLoadMore(id, currentPage + 1);
поправил

2021-05-28 09:51 UTC, Kid-Guru commented on app/javascript/components/TaskBoard/TaskBoard.js
> +  useEffect(() => loadBoard(), []);
поправил

2021-05-28 09:51 UTC, Kid-Guru commented on app/javascript/components/TaskBoard/TaskBoard.js
> +  useEffect(() => generateBoard(), [boardCards]);
поправил

2021-05-31 13:55 UTC, Ensaphelon requested changes

2021-05-31 13:55 UTC, Ensaphelon commented on app/javascript/components/ColumnHeader/ColumnHeader.js
> +          <IconButton aria-label="Load more" onClick={() => handleMoreLoad()}>
onClick={handleMoreLoad}

2021-05-31 13:55 UTC, Ensaphelon commented on app/javascript/components/TaskBoard/TaskBoard.js
> +        setBoard(() => state.columns);
а зачем нам менять стейт таким образом? Наверное он и не должен меняться вовсе? Данных то новых нету?

2021-06-01 11:17 UTC, Kid-Guru commented on app/javascript/components/TaskBoard/TaskBoard.js
> +        setBoard(() => state.columns);
Исправил. Дописал логику дозагрузки задач

2021-06-01 11:17 UTC, Kid-Guru commented on app/javascript/components/ColumnHeader/ColumnHeader.js
> +          <IconButton aria-label="Load more" onClick={() => handleMoreLoad()}>
исправил

2021-06-01 12:24 UTC, Ensaphelon approved these changes

2021-06-01 13:24 UTC, merged