Feature/assignee
Kid-Guru/task_manager pull request #19
Opened 2021-06-01 13:34 UTC by Kid-Guru

2021-06-02 16:45 UTC, greybutton requested changes

2021-06-02 16:45 UTC, greybutton commented on app/javascript/components/EditPopup/EditPopup.js
> +import TaskPresenter from '../../presenters/TaskPresenter';
'presenters/TaskPresenter';

2021-06-02 16:45 UTC, greybutton commented on app/javascript/components/EditPopup/Form.js
> +import UserSelect from '../UserSelect/UserSelect';
'components/UserSelect'

2021-06-02 16:45 UTC, greybutton commented on app/javascript/components/EditPopup/Form.js
> +      />
это поле доступно только когда редактирование

2021-06-02 16:45 UTC, greybutton commented on app/javascript/repositories/UsersRepository.js
> +    const path = routes.apiV1UsersPath(id);
apiV1UserPath

2021-06-02 16:45 UTC, greybutton commented on app/javascript/routes/ApiRoutes.js
> + */
как генерируешь этот файл? немного отличается от остальных

2021-06-04 04:35 UTC, Kid-Guru commented on app/javascript/components/EditPopup/EditPopup.js
> +import TaskPresenter from '../../presenters/TaskPresenter';
Исправил

2021-06-04 04:35 UTC, Kid-Guru commented on app/javascript/components/EditPopup/Form.js
> +import UserSelect from '../UserSelect/UserSelect';
Исправил

2021-06-04 04:36 UTC, Kid-Guru commented on app/javascript/components/EditPopup/Form.js
> +      />
Исправил

2021-06-04 04:36 UTC, Kid-Guru commented on app/javascript/repositories/UsersRepository.js
> +    const path = routes.apiV1UsersPath(id);
Исправил

2021-06-04 04:37 UTC, Kid-Guru commented on app/javascript/routes/ApiRoutes.js
> + */
Командой rails js_routes:generate

2021-06-04 07:12 UTC, greybutton approved these changes

2021-06-11 15:06 UTC, merged